behaviors:
  EnemyAI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 5120
      learning_rate: 0.00003
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
    behavioral_cloning:
      strength: 1.0
      demo_path: Demonstrations
      steps: 0
