behaviors:
  EnemyAI: # 名字必須保持一樣
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0001
      beta: 0.001
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 1
      learning_rate_schedule: linear
      beta_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      memory:
        sequence_length: 128  # AI 能「回想」過去多少個步驟的資訊
        memory_size: 256
      
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    checkpoint_interval: 500000
    keep_checkpoints: 20
    max_steps: 5000000
    time_horizon: 256
    summary_freq: 500000